config/routes.rb
Heatmap::Application.routes.draw do
  resources :data_categories

  resources :data
  
  resources :groups do
    member do
	  get 'leave'
	end
  end

  resources :group_requests do
    member do
	  get 'accept'
	  get 'decline'
	end
  end

  resources :group_invites do 
    member do
	  get 'accept'
	  get 'decline'
	end
  end

  resources :maps do
    member do
	  get 'draw'
	end
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/group_invite.rb
class GroupInvite < ActiveRecord::Base
  belongs_to :inviter, class_name: "User"
  belongs_to :invitee, class_name: "User"
  belongs_to :group
end

app/controllers/group_invites_controller.rb
class GroupInvitesController < ApplicationController
  before_action :set_group_invite, only: [:show, :edit, :update, :destroy]

  # GET /group_invites
  # GET /group_invites.json
  def index
    @group_invites = GroupInvite.all
  end

  # GET /group_invites/1
  # GET /group_invites/1.json
  def show
  end

  # GET /group_invites/new
  def new
    @group_invite = GroupInvite.new
  end

  # GET /group_invites/1/edit
  def edit
  end

  # POST /group_invites
  # POST /group_invites.json
  def create
    @group_invite = GroupInvite.new(group_invite_params)

    respond_to do |format|
      if @group_invite.save
        format.html { redirect_to @group_invite, notice: 'Group invite was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group_invite }
      else
        format.html { render action: 'new' }
        format.json { render json: @group_invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_invites/1
  # PATCH/PUT /group_invites/1.json
  def update
    respond_to do |format|
      if @group_invite.update(group_invite_params)
        format.html { redirect_to @group_invite, notice: 'Group invite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group_invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_invites/1
  # DELETE /group_invites/1.json
  def destroy
    @group_invite.destroy
    respond_to do |format|
      format.html { redirect_to group_invites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_invite
      @group_invite = GroupInvite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_invite_params
      params.require(:group_invite).permit(:inviter_id, :group_id, :invitee_id, :message, :accepted, :declined)
    end
end

app/helpers/group_invites_helper.rb
module GroupInvitesHelper
end

app/views/group_invites/_form.html.erb
<%= form_for(@group_invite) do |f| %>
  <% if @group_invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_invite.errors.count, "error") %> prohibited this group_invite from being saved:</h2>

      <ul>
      <% @group_invite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_id %><br>
	<%= f.collection_select :group_id, current_user.groups, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :invitee_id %><br>
    <%= f.text_field :invitee_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit '초대하기', class:'btn btn-mini btn-default'%>
  </div>
<% end %>

app/views/group_invites/edit.html.erb
<h1>Editing group_invite</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_invite %> |
<%= link_to 'Back', group_invites_path %>

app/views/group_invites/index.html.erb
<h1>Listing group_invites</h1>

<table>
  <thead>
    <tr>
      <th>Inviter</th>
      <th>Group</th>
      <th>Invitee</th>
      <th>Message</th>
      <th>Accepted</th>
      <th>Declined</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @group_invites.each do |group_invite| %>
      <tr>
        <td><%= group_invite.inviter %></td>
        <td><%= group_invite.group %></td>
        <td><%= group_invite.invitee %></td>
        <td><%= group_invite.message %></td>
        <td><%= group_invite.accepted %></td>
        <td><%= group_invite.declined %></td>
        <td><%= link_to 'Show', group_invite %></td>
        <td><%= link_to 'Edit', edit_group_invite_path(group_invite) %></td>
        <td><%= link_to 'Destroy', group_invite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group invite', new_group_invite_path %>

app/views/group_invites/new.html.erb
<h1>New group_invite</h1>

<%= render 'form' %>

<%= link_to 'Back', group_invites_path %>

app/views/group_invites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Inviter:</strong>
  <%= @group_invite.inviter %>
</p>

<p>
  <strong>Group:</strong>
  <%= @group_invite.group %>
</p>

<p>
  <strong>Invitee:</strong>
  <%= @group_invite.invitee %>
</p>

<p>
  <strong>Message:</strong>
  <%= @group_invite.message %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @group_invite.accepted %>
</p>

<p>
  <strong>Declined:</strong>
  <%= @group_invite.declined %>
</p>

<%= link_to 'Edit', edit_group_invite_path(@group_invite) %> |
<%= link_to 'Back', group_invites_path %>