config/routes.rb
Heatmap::Application.routes.draw do
  resources :data_categories

  resources :data
  
  resources :groups do
    member do
	  get 'leave'
	end
  end

  resources :group_requests do
    member do
	  get 'accept'
	  get 'decline'
	end
  end

  resources :group_invites do 
    member do
	  get 'accept'
	  get 'decline'
	end
  end

  resources :maps do
    member do
	  get 'draw'
	end
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :group_invites
  has_many :group_requests
  has_many :maps
  
  after_save do |group|
    new_owner = group.user
	new_owner.groups << group if !new_owner.groups.include?(group)
	new_owner.save
  end
  
  def to_s
    name
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :leave]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
	@group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
  
  def leave
    current_user.groups.delete(@group)
	redirect_to @group, notice: 'You have left this group.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :user_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-mini btn-default'%>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1><%=t('label.editing', model: t('activerecord.models.group'))%></h1>

<%= render 'form' %>

<%= link_to t('label.show'), @group %> |
<%= link_to t('label.back'), groups_path %>

app/views/groups/index.html.erb
<h3><%=t 'activerecord.models.group'%></h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th><%= t 'activerecord.attributes.group.name'%></th>
      <th><%= t 'activerecord.attributes.group.owner'%></th>
	  <% if can? :manage, Group %>
      <th></th>
      <th></th>
	  <% end %>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group %></td>
        <td><%= group.user.name %></td>
		<% if can? :manage, Group %>
        <td><%= link_to t('label.edit'), edit_group_path(group), class: 'btn btn-mini btn-default' %></td>
        <td><%= link_to t('label.delete'), group, method: :delete, data: { confirm: t('label.are_you_sure') }, class: 'btn btn-mini btn-danger' %></td>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<% if can? :manage, Group %>
  <%= link_to t('label.new', model: t('activerecord.models.group')), new_group_path %>
<% end %>

app/views/groups/new.html.erb
<h1><%=t 'label.new', model: t('activerecord.models.group')%></h1>

<%= render 'form' %>

<%= link_to t('label.back'), groups_path %>

app/views/groups/show.html.erb
<p>
  <strong><%=t 'activerecord.attributes.group.name'%>:</strong>
  <%= @group.name %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.group.owner'%>:</strong>
  <%= @group.user %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.group.members'%>:</strong>
  <%= @group.users.count %>
</p>

<% if can? :manage, @group %>
<p><%= link_to "가입 신청 목록 보기 
(#{@group.group_requests.where(accepted:nil,declined:nil).count})", 
group_requests_url(fresh:true) %><p>
<% end %>

<% if !@group.users.include? (current_user) %>
<p><%= link_to '그룹 가입', new_group_request_path(group_id: @group.id) %></p>
<% else %>
<p><%= link_to '그룹 나가기', leave_group_path(@group), data: { confirm: t('label.are_you_sure')}, class: 'btn btn-small btn-danger pull-right' %></p>
<% end %>

<% if can? :update, @group %>
  <%= link_to t('label.edit'), edit_group_path(@group) %> |
<% end %>
<%= link_to t('label.back'), groups_path %>