config/routes.rb
Heatmap::Application.routes.draw do
  resources :data_categories

  resources :data
  
  resources :groups do
    member do
	  get 'leave'
	end
  end

  resources :group_requests do
    member do
	  get 'accept'
	  get 'decline'
	end
  end

  resources :group_invites do 
    member do
	  get 'accept'
	  get 'decline'
	end
  end

  resources :maps do
    member do
	  get 'draw'
	end
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/group_request.rb
class GroupRequest < ActiveRecord::Base
  belongs_to :requester, class_name: "User"
  belongs_to :group
  
  def fresh
    accepted.nil? && declined.nil?
  end
end

app/controllers/group_requests_controller.rb
class GroupRequestsController < ApplicationController
  before_action :set_group_request, only: [:show, :edit, :update, :destroy, :accept, :decline]

  # GET /group_requests
  # GET /group_requests.json
  def index
    authorize! :index, @group_requests
    if can? :manage, GroupRequest
	  @group_requests = GroupRequest.scoped
	  @group_requests = @group_requests.where(accepted:nil, declined:nil) if params[:fresh]
	else
	  @group_requests = current_user.group_requests
	end
  end

  # GET /group_requests/1
  # GET /group_requests/1.json
  def show
    authorize! :show, @group_request
  end

  # GET /group_requests/new
  def new
    @group_request = GroupRequest.new
	group = Group.find(params[:group_id]) if params[:group_id]
  end

  # GET /group_requests/1/edit
  def edit
  end

  # POST /group_requests
  # POST /group_requests.json
  def create
    @group_request = GroupRequest.new(group_request_params)
	@group_request.requester = current_user
	
	authorize! :create, @group_request

    respond_to do |format|
      if @group_request.save
        format.html { redirect_to @group_request.group, notice: t('notice.created', model:GroupRequest) }
        format.json { render action: 'show', status: :created, location: @group_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @group_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_requests/1
  # PATCH/PUT /group_requests/1.json
  def update
    authorize! :update, @group_request
    respond_to do |format|
      if @group_request.update(group_request_params)
        format.html { redirect_to @group_request, notice: t('notice.updated', model:GroupRequest) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group_request.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def accept
    authorize! :accept, @group_request
    new_member = @group_request.requester
	group = @group_request.group
	if !new_member.groups.include? (group)
	  new_member.groups << group
	  new_member.save
	end
	@group_request.requester.group_requests.where(accepted:nil,declined:nil).update_all(accepted:Time.now)
	redirect_to context_return_url
  end
  
  def decline
    authorize! :decline, @group_request
	@group_request.requester.group_requests.
	  where(accepted:nil,declined:nil).
	  update_all(declined:Time.now)
	redirect_to context_return_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_request
      @group_request = GroupRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_request_params
      params.require(:group_request).permit(:group_id, :message)
    end
	
	def context_return_url
	  if params[:fresh]
	    group_requests_path(fresh:true)
	  else
	    group_requests_path
	  end
	end
end

app/helpers/group_requests_helper.rb
module GroupRequestsHelper
end

app/views/group_requests/_form.html.erb
<%= form_for(@group_request) do |f| %>
  <% if @group_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_request.errors.count, "error") %> prohibited this group_request from being saved:</h2>

      <ul>
      <% @group_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.collection_select :group_id, Group.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>

  <div class="actions">
    <%= f.submit '가입', class: 'btn btn-mini btn-default'%>
  </div>
<% end %>

app/views/group_requests/edit.html.erb
<h1>Editing group_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_request %> |
<%= link_to 'Back', group_requests_path %>

app/views/group_requests/index.html.erb
<h1>Group Requests (<%=params[:fresh] ? '신규' : '모두'%>)</h1>
<% if params[:fresh] %>
  <%= link_to '모두 보기', group_requests_url %>
<% else %>
  <%= link_to '신규만 보기', group_requests_url(fresh:true) %>
<% end %>

<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Requester</th>
      <th>Group</th>
      <th>Message</th>
      <th>Accepted</th>
      <th>Declined</th>
	  <% if can? :manage, GroupRequest %>
      <th></th>
      <th></th>
	  <% end %>
    </tr>
  </thead>

  <tbody>
    <% @group_requests.each do |group_request| %>
      <tr>
        <td><%= group_request.requester %></td>
        <td><%= group_request.group %></td>
        <td><%= group_request.message %></td>
        <td><%= group_request.accepted %></td>
        <td><%= group_request.declined %></td>
		<% if can? :manage, GroupRequest %>
        <td><%= link_to 'Accept', accept_group_request_path(group_request)  if group_request.fresh%></td>
		<td><%= link_to 'Decline', decline_group_request_path(group_request) if group_request.fresh%></td>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Group request', new_group_request_path %>

app/views/group_requests/new.html.erb
<h1>New group_request</h1>

<%= render 'form' %>

<%= link_to 'Back', group_requests_path %>

app/views/group_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requester:</strong>
  <%= @group_request.requester %>
</p>

<p>
  <strong>Group:</strong>
  <%= @group_request.group %>
</p>

<p>
  <strong>Message:</strong>
  <%= @group_request.message %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @group_request.accepted %>
</p>

<p>
  <strong>Declined:</strong>
  <%= @group_request.declined %>
</p>

<%= link_to 'Edit', edit_group_request_path(@group_request) %> |
<%= link_to 'Back', group_requests_path %>