config/routes.rb
Heatmap::Application.routes.draw do
  resources :data_categories

  resources :data
  
  resources :groups do
    member do
	  get 'leave'
	end
  end

  resources :group_requests do
    member do
	  get 'accept'
	  get 'decline'
	end
  end

  resources :group_invites do 
    member do
	  get 'accept'
	  get 'decline'
	end
  end

  resources :maps do
    member do
	  get 'draw'
	end
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/views/layouts/_footer.html.erb
<div class="footer">
<img src="http://tjkfem.or.kr/bbs/images/copy.gif"/>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if can? :manage, DataCategory %>
  <li><%= link_to '데이터분류', data_categories_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to '지도', maps_path %></li>
  <li><%= link_to '그룹', groups_path %></li>
<% end %>

<% if can? :manage, User %>
  <li><%= link_to '사용자관리', users_path %></li>
<% end %>

<% if user_signed_in? %>
  <li><%= link_to '계정관리', edit_user_registration_path %></li>
  <li><%= link_to '로그아웃', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to '계정만들기', new_user_registration_path %></li>
  <li><%= link_to '로그인', new_user_session_path %></li>
<% end %>

<li>&nbsp;</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Heatmap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Heatmap" %>">
    <%= stylesheet_link_tag 'application', media: 'all'  %>
	<script src="https://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>
	<script src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer_compiled.js" type="text/javascript"></script>
    <%= javascript_include_tag 'application' %>
	<%= javascript_include_tag params[:controller] %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
	   <div class="push"></div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>